server:
  port: 8082

spring:
  application:
    name: transacciones-service
  datasource:
    url: jdbc:postgresql://localhost:5432/transacciones_db
    username: transacciones_user
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

smartcash:
  jwt:
    # DEBE ser exactamente el mismo secreto que usuarios-auth
    secret: ${JWT_SECRET}

