server:
  port: 8081

spring:
  application:
    name: usuarios-auth
  datasource:
    url: jdbc:postgresql://localhost:5432/usuarios_db
    username: usuarios_user
    password: ${DB_PASSWORD:Usuario58}
  jpa:
    hibernate:
      ddl-auto: update    # en produccion: usar migraciones (Flyway/Liquibase), no ddl-auto
    show-sql: true
    properties:
      hibernate:
        format_sql: true

smartcash:
  jwt:
    secret: ${JWT_SECRET:una-clave-secreta-muy-larga-cambiar-en-produccion-1234567890}
    expiracion-ms: 3600000   # 1 hora
