server.port=8081

spring.application.name=usuarios-auth

spring.datasource.url=jdbc:postgresql://localhost:5432/usuarios_db
spring.datasource.username=usuarios_user
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

smartcash.jwt.secret=${JWT_SECRET}
smartcash.jwt.expiracion-ms=3600000
