server.port=8083

spring.application.name=notificaciones-service

smartcash.notificaciones.brevo.api-url=https://api.brevo.com/v3/smtp/email
smartcash.notificaciones.brevo.api-key=${EMAIL_API_KEY:mock-key}
smartcash.notificaciones.remitente.nombre=SmartCash
smartcash.notificaciones.remitente.email=soporte@smartcash.com
